import { UnidadSalud } from '@/features/medical-unit/interfaces/medical-unit';

export const DIAS_CATALOGO = [
  { id: 1, descripcion: 'LUNES' },
  { id: 2, descripcion: 'MARTES' },
  { id: 3, descripcion: 'MIÉRCOLES' },
  { id: 4, descripcion: 'JUEVES' },
  { id: 5, descripcion: 'VIERNES' },
  { id: 6, descripcion: 'SÁBADO' },
  { id: 7, descripcion: 'DOMINGO' },
];

export const TIPO_PERSONAL_CATALOGO = [
  { id: 1, descripcion: 'MÉDICA (O) PASANTE' },
  { id: 2, descripcion: 'MÉDICA (O) GENERAL' },
  { id: 3, descripcion: 'MÉDICA (O) RESIDENTE' },

  { id: 4, descripcion: 'MÉDICA (O) ESPECIALISTA' },
  { id: 5, descripcion: 'PASANTE DE ENFERMERÍA' },
  { id: 6, descripcion: 'ENFERMERA (O)' },
  { id: 7, descripcion: 'PASANTE DE NUTRICIÓN' },
  { id: 8, descripcion: 'NUTRIÓLOGA (O)' },
  { id: 9, descripcion: 'HOMEÓPATA' },
  { id: 10, descripcion: 'MÉDICA (O) TRADICIONAL INDÍGENA' },
  { id: 11, descripcion: 'TAPS' },
  { id: 12, descripcion: 'PASANTE ODONTOLOGIA' },
  { id: 13, descripcion: 'ODONTOLOGA (O)' },
  { id: 14, descripcion: 'ODONTOLOGA(O) ESPECIALISTA' },
  { id: 15, descripcion: 'PASANTE DE PSICOLOGÍA' },
  { id: 16, descripcion: 'PSICÓLOGA (O)' },
  { id: 17, descripcion: 'RESIDENTE DE PSIQUIATRÍA' },
  { id: 18, descripcion: 'PSIQUIATRA' },
  { id: 19, descripcion: 'MÉDICA(O) GENERAL HABILITADA(O) PARA SALUD MENTAL' },
  { id: 20, descripcion: 'LICENCIADA(O) EN ENFERMERÍA Y OBSTETRICIA' },
  { id: 21, descripcion: 'PARTERA(O) TÉCNICA' },
  { id: 22, descripcion: 'PROMOTOR(A) DE SALUD' },
  { id: 23, descripcion: 'TÉCNICA(O) EN ODONTOLOGÍA' },
  {
    id: 24,
    descripcion: 'MÉDICA(O) ESPECIALISTA HABILITADA(O) PARA SALUD MENTAL',
  },
  { id: 25, descripcion: 'LICENCIADA (O) EN GERONTOLOGÍA' },
  {
    id: 26,
    descripcion: 'PERSONAL CAPACITADO O HABILITADO PARA ATENCIÓN A DISTANCIA',
  },
  { id: 27, descripcion: 'PASANTE DE GERONTOLOGÍA' },
  { id: 28, descripcion: 'PARTERA(O) PROFESIONAL' },
  { id: 29, descripcion: 'ACUPUNTURISTA' },
  { id: 30, descripcion: 'TRABAJADORA(OR) SOCIAL' },
  { id: 99, descripcion: 'APOYO ADMINISTRATIVO' },
  { id: 98, descripcion: 'RECEPCIONISTA' },
];

export const ESCOLARIDAD_CATALOGO = [
  { id: 0, descripcion: 'NO ESPECIFICADO' },
  { id: 1, descripcion: 'NINGUNA' },
  { id: 31, descripcion: 'PRIMARIA COMPLETA' },
  { id: 32, descripcion: 'PRIMARIA INCOMPLETA' },
  { id: 51, descripcion: 'SECUNDARIA COMPLETA' },
  { id: 52, descripcion: 'SECUNDARIA INCOMPLETA' },
  { id: 71, descripcion: 'BACHILLERATO O PREPARATORIA COMPLETA' },
  { id: 72, descripcion: 'BACHILLERATO O PREPARATORIA INCOMPLETA' },
  { id: 81, descripcion: 'LICENCIATURA O PROFESIONAL COMPLETO' },
  { id: 82, descripcion: 'LICENCIATURA O PROFESIONAL INCOMPLETO' },
  { id: 88, descripcion: 'NO APLICA' },
  { id: 99, descripcion: 'SE IGNORA' },
  { id: 101, descripcion: 'POSGRADO COMPLETO' },
  { id: 102, descripcion: 'POSGRADO INCOMPLETO' },
  { id: 111, descripcion: 'TÉCNICO TERMINAL CON SECUNDARIA COMPLETA' },
  { id: 112, descripcion: 'TÉCNICO TERMINAL CON SECUNDARIA INCOMPLETA' },
  { id: 121, descripcion: 'PREESCOLAR COMPLETA' },
  { id: 122, descripcion: 'PREESCOLAR INCOMPLETA' },
  { id: 131, descripcion: 'TÉCNICO TERMINAL CON PREPARATORIA COMPLETA' },
  { id: 132, descripcion: 'TÉCNICO TERMINAL CON PREPARATORIA INCOMPLETA' },
];

export const DERECHOHABIENCIA_CATALOGO = [
  { id: 0, descripcion: 'NO ESPECIFICADO' },
  { id: 1, descripcion: 'NINGUNA' },
  { id: 2, descripcion: 'IMSS' },
  { id: 3, descripcion: 'ISSSTE' },
  { id: 4, descripcion: 'PEMEX' },
  { id: 5, descripcion: 'SEDENA' },
  { id: 6, descripcion: 'SEMAR' },
  { id: 7, descripcion: 'SEGURO POPULAR' },
  { id: 8, descripcion: 'OTRA' },
  { id: 10, descripcion: 'IMSS Bienestar' },
  { id: 11, descripcion: 'ISSFAM' },
  { id: 13, descripcion: 'INSABI' },
  { id: 14, descripcion: 'OPD IMSS BIENESTAR' },
  { id: 88, descripcion: 'NO APLICA' },
  { id: 99, descripcion: 'SE IGNORA' },
];

export const ENTIDAD_FEDERATIVA_CATALOGO = [
  { id: 0, descripcion: 'NO ESPECIFICADO', abreviatura: 'NE' },
  { id: 1, descripcion: 'AGUASCALIENTES', abreviatura: 'AS' },
  { id: 2, descripcion: 'BAJA CALIFORNIA', abreviatura: 'BC' },
  { id: 3, descripcion: 'BAJA CALIFORNIA SUR', abreviatura: 'BS' },
  { id: 4, descripcion: 'CAMPECHE', abreviatura: 'CC' },
  { id: 5, descripcion: 'COAHUILA DE ZARAGOZA', abreviatura: 'CL' },
  { id: 6, descripcion: 'COLIMA', abreviatura: 'CM' },
  { id: 7, descripcion: 'CHIAPAS', abreviatura: 'CS' },
  { id: 8, descripcion: 'CHIHUAHUA', abreviatura: 'CH' },
  { id: 9, descripcion: 'CIUDAD DE MEXICO', abreviatura: 'DF' },
  { id: 10, descripcion: 'DURANGO', abreviatura: 'DG' },
  { id: 11, descripcion: 'GUANAJUATO', abreviatura: 'GT' },
  { id: 12, descripcion: 'GUERRERO', abreviatura: 'GR' },
  { id: 13, descripcion: 'HIDALGO', abreviatura: 'HG' },
  { id: 14, descripcion: 'JALISCO', abreviatura: 'JC' },
  { id: 15, descripcion: 'MEXICO', abreviatura: 'MC' },
  { id: 16, descripcion: 'MICHOACAN DE OCAMPO', abreviatura: 'MN' },
  { id: 17, descripcion: 'MORELOS', abreviatura: 'MS' },
  { id: 18, descripcion: 'NAYARIT', abreviatura: 'NT' },
  { id: 19, descripcion: 'NUEVO LEON', abreviatura: 'NL' },
  { id: 20, descripcion: 'OAXACA', abreviatura: 'OC' },
  { id: 21, descripcion: 'PUEBLA', abreviatura: 'PL' },
  { id: 22, descripcion: 'QUERETARO', abreviatura: 'QT' },
  { id: 23, descripcion: 'QUINTANA ROO', abreviatura: 'QR' },
  { id: 24, descripcion: 'SAN LUIS POTOSI', abreviatura: 'SP' },
  { id: 25, descripcion: 'SINALOA', abreviatura: 'SL' },
  { id: 26, descripcion: 'SONORA', abreviatura: 'SR' },
  { id: 27, descripcion: 'TABASCO', abreviatura: 'TC' },
  { id: 28, descripcion: 'TAMAULIPAS', abreviatura: 'TS' },
  { id: 29, descripcion: 'TLAXCALA', abreviatura: 'TL' },
  { id: 30, descripcion: 'VERACRUZ DE IGNACIO DE LA LLAVE', abreviatura: 'VZ' },
  { id: 31, descripcion: 'YUCATAN', abreviatura: 'YN' },
  { id: 32, descripcion: 'ZACATECAS', abreviatura: 'ZS' },
  { id: 88, descripcion: 'NO APLICA', abreviatura: 'NA' },
  { id: 99, descripcion: 'SE IGNORA', abreviatura: 'SI' },
];

export const ESTADO_CONYUGAL_CATALOGO = [
  { id: 0, descripcion: 'NO ESPECIFICADO' },
  { id: 1, descripcion: 'SOLTERO(A)' },
  { id: 2, descripcion: 'VIUDO(A)' },
  { id: 3, descripcion: 'DIVORCIADO(A)' },
  { id: 4, descripcion: 'UNION LIBRE' },

  { id: 5, descripcion: 'CASADO(A)' },
  { id: 6, descripcion: 'SEPARADO(A)' },
  { id: 8, descripcion: 'NO APLICA' },
  { id: 9, descripcion: 'SE IGNORA' },
];

export const SERVICIO_ATENCION_CATALOGO = [
  { id: 1, descripcion: 'ATENCIÓN A ADICCIONES' },
  { id: 2, descripcion: 'ATENCIÓN A LA VIOLENCIA' },
  { id: 3, descripcion: 'CIRUGÍA' },
  { id: 4, descripcion: 'CONSULTA EXTERNA GENERAL' },
  { id: 5, descripcion: 'GINECOOBSTETRICIA' },
  { id: 6, descripcion: 'HOMEOPATÍA' },
  { id: 7, descripcion: 'MEDICINA INTERNA' },
  { id: 8, descripcion: 'MEDICINA PREVENTIVA' },
  { id: 9, descripcion: 'MEDICINA TRADICIONAL' },
  { id: 10, descripcion: 'ODONTOLOGÍA' },
  { id: 11, descripcion: 'ODONTOLOGÍA ESPECIALIZADA' },
  { id: 12, descripcion: 'ODONTOPEDIATRÍA' },
  { id: 13, descripcion: 'OFTALMOLOGÍA' },
  { id: 14, descripcion: 'OTORRINOLARINGOLOGÍA' },
  { id: 15, descripcion: 'PAIDOPSIQUIATRÍA' },
  { id: 16, descripcion: 'PEDIATRÍA' },
  { id: 17, descripcion: 'PLANIFICACIÓN FAMILIAR' },
  { id: 18, descripcion: 'PRECONSULTA' },
  { id: 19, descripcion: 'PSICOGERIATRÍA' },
  { id: 20, descripcion: 'PSICOLOGÍA' },
  { id: 21, descripcion: 'PSIQUIATRÍA' },
  { id: 22, descripcion: 'SERVICIO AMIGABLE' },
  { id: 23, descripcion: 'TRAUMATOLOGÍA Y ORTOPEDIA' },
  { id: 24, descripcion: 'ACUPUNTURA' },
  { id: 25, descripcion: 'ALERGOLOGÍA' },
  { id: 26, descripcion: 'ANESTESIOLOGÍA' },
  { id: 27, descripcion: 'ANGIOLOGÍA' },
  { id: 28, descripcion: 'AUDIOLOGÍA, OTONEUROLOGÍA Y FONIATRÍA' },
  { id: 29, descripcion: 'BRIGADA O CONSULTA EN CASA' },
  { id: 30, descripcion: 'CARDIOLOGÍA' },
  { id: 31, descripcion: 'CIRUGÍA MAXILOFACIAL' },
  { id: 32, descripcion: 'CIRUGÍA PLÁSTICA Y RECONSTRUCTIVA' },
  { id: 33, descripcion: 'CLÍNICA DE DOWN' },
  { id: 34, descripcion: 'DERMATOLOGÍA' },
  { id: 35, descripcion: 'ENDOCRINOLOGÍA' },
  { id: 36, descripcion: 'EPIDEMIOLOGÍA' },
  { id: 37, descripcion: 'GASTROENTEROLOGÍA' },
  { id: 38, descripcion: 'GENÉTICA' },
  { id: 39, descripcion: 'GERIATRÍA' },
  { id: 40, descripcion: 'HEMATOLOGÍA' },
  { id: 41, descripcion: 'INFECTOLOGÍA' },
  { id: 42, descripcion: 'INMUNOLOGÍA' },
  { id: 43, descripcion: 'MEDICINA INTEGRADA' },
  { id: 44, descripcion: 'MEDICINA NUCLEAR E IMAGENOLOGÍA MOLECULAR' },
  { id: 45, descripcion: 'NEFROLOGÍA' },
  { id: 46, descripcion: 'NEONATOLOGÍA' },
  { id: 47, descripcion: 'NEUMOLOGÍA' },
  { id: 48, descripcion: 'NEUROCIRUGÍA' },
  { id: 49, descripcion: 'NEUROLOGÍA' },
  { id: 50, descripcion: 'NUTRICIÓN' },
  { id: 51, descripcion: 'ONCOLOGÍA' },
  { id: 52, descripcion: 'OPTOMETRIA' },
  { id: 53, descripcion: 'PROCTOLOGÍA' },
  { id: 54, descripcion: 'REHABILITACIÓN' },
  { id: 55, descripcion: 'REUMATOLOGÍA' },
  { id: 56, descripcion: 'TAES' },
  { id: 57, descripcion: 'TRANSPLANTES' },
  { id: 58, descripcion: 'UNIDAD DE QUEMADOS' },
  { id: 59, descripcion: 'UROLOGÍA' },
  { id: 60, descripcion: 'DETECCIONES' },
  { id: 61, descripcion: 'CUIDADOS PALIATIVOS' },
  { id: 62, descripcion: 'GERONTOLOGÍA' },
  {
    id: 63,
    descripcion: 'UNIDAD DE CONTACTO PARA INTERCONSULTA A DISTANCIA (UCID)',
  },
  { id: 64, descripcion: 'CALLCENTER' },
  { id: 65, descripcion: 'ÁREA DE URGENCIAS' },
  { id: 66, descripcion: 'ÁREA DE HOSPITALIZACIÓN' },
  { id: 67, descripcion: 'TERAPIA INTENSIVA O INTERMEDIA' },
  { id: 68, descripcion: 'ÁREA DE CONSULTA EXTERNA' },
  { id: 69, descripcion: 'MEDICINA FAMILIAR' },
  { id: 70, descripcion: 'SERVICIO ESPECIALIZADO PARA LA ATENCIÓN DE VIH/ITS' },
  { id: 71, descripcion: 'SERVICIO DE ATENCIÓN INTEGRAL A LA SALUD (SAIS)' },
  { id: 72, descripcion: 'ONCOLOGÍA PEDIÁTRICA' },
  { id: 88, descripcion: 'OTROS' },
  { id: 99, descripcion: 'ADMINISTRACIÓN' },
];

export const PAIS_CATALOGO = [
  { id: 1, descripcion: 'REPUBLICA DEL ECUADOR', order: 58 },
  { id: 2, descripcion: 'REPUBLICA ARABE DE EGIPTO', order: 60 },
  { id: 3, descripcion: 'ARUBA', order: 3 },
  { id: 4, descripcion: 'REPUBLICA ISLAMICA DE AFGANISTAN', order: 4 },
  { id: 5, descripcion: 'REPUBLICA DE ANGOLA', order: 5 },
  { id: 6, descripcion: 'ANGUILA*', order: 6 },
  { id: 7, descripcion: 'REPUBLICA DE ALBANIA', order: 7 },
  { id: 8, descripcion: 'PRINCIPADO DE ANDORRA', order: 8 },
  { id: 10, descripcion: 'EMIRATOS ARABES UNIDOS', order: 9 },
  { id: 11, descripcion: 'REPUBLICA ARGENTINA', order: 10 },
  { id: 12, descripcion: 'REPUBLICA DE ARMENIA', order: 11 },
  { id: 13, descripcion: 'SAMOA AMERICANA*', order: 12 },
  { id: 16, descripcion: 'ANTIGUA Y BARBUDA', order: 13 },
  { id: 17, descripcion: 'MANCOMUNIDAD DE AUSTRALIA', order: 14 },
  { id: 18, descripcion: 'REPUBLICA DE AUSTRIA', order: 15 },
  { id: 19, descripcion: 'REPUBLICA DE AZERBAIYAN', order: 16 },
  { id: 20, descripcion: 'REPUBLICA DE BURUNDI', order: 17 },
  { id: 21, descripcion: 'REINO DE BELGICA', order: 18 },
  { id: 22, descripcion: 'REPUBLICA DE BENIN', order: 19 },
  { id: 23, descripcion: 'BURKINA FASO', order: 20 },
  { id: 24, descripcion: 'REPUBLICA POPULAR DE BANGLADESH', order: 21 },
  { id: 25, descripcion: 'REPUBLICA DE BULGARIA', order: 22 },
  { id: 26, descripcion: 'REINO DE BAHREIN', order: 23 },
  { id: 27, descripcion: 'MANCOMUNIDAD DE LAS BAHAMAS', order: 24 },
  { id: 28, descripcion: 'BOSNIA Y HERZEGOVINA', order: 25 },
  { id: 29, descripcion: 'REPUBLICA DE BIELORRUSIA', order: 26 },
  { id: 30, descripcion: 'BELICE', order: 27 },
  { id: 31, descripcion: 'BERMUDAS*', order: 28 },
  { id: 32, descripcion: 'ESTADO PLURINACIONAL DE BOLIVIA', order: 29 },
  { id: 33, descripcion: 'REPUBLICA FEDERATIVA DE BRASIL', order: 30 },
  { id: 34, descripcion: 'BARBADOS', order: 31 },
  { id: 35, descripcion: 'SULTANATO DE BRUNEI', order: 32 },
  { id: 36, descripcion: 'REINO DE BUTAN', order: 33 },
  { id: 39, descripcion: 'REPUBLICA DE BOTSUANA', order: 34 },
  { id: 40, descripcion: 'REPUBLICA CENTROAFRICANA', order: 35 },
  { id: 41, descripcion: 'CANADA', order: 36 },
  { id: 43, descripcion: 'REPUBLICA DE COSTA DE MARFIL', order: 37 },
  { id: 44, descripcion: 'REPUBLICA DE CAMERUN', order: 38 },
  { id: 45, descripcion: 'REPUBLICA DEL CONGO', order: 39 },
  { id: 47, descripcion: 'ISLAS COOK', order: 40 },
  { id: 48, descripcion: 'REPUBLICA DE COLOMBIA', order: 41 },
  { id: 49, descripcion: 'UNION DE LAS COMORAS', order: 42 },
  { id: 50, descripcion: 'REPUBLICA DE CABO VERDE', order: 43 },
  { id: 51, descripcion: 'REPUBLICA DE COSTA RICA', order: 44 },
  { id: 53, descripcion: 'REPUBLICA DE CUBA', order: 45 },
  { id: 55, descripcion: 'ISLAS CAIMAN*', order: 46 },
  { id: 56, descripcion: 'REPUBLICA DE CHIPRE', order: 47 },
  { id: 57, descripcion: 'REPUBLICA CHECA', order: 48 },
  { id: 58, descripcion: 'CONFEDERACION SUIZA', order: 49 },
  { id: 59, descripcion: 'REPUBLICA DE CHILE', order: 50 },
  { id: 60, descripcion: 'REPUBLICA POPULAR CHINA', order: 51 },
  { id: 61, descripcion: 'REPUBLICA FEDERAL DE ALEMANIA', order: 52 },
  { id: 62, descripcion: 'REPUBLICA DE YIBUTI', order: 53 },
  { id: 63, descripcion: 'MANCOMUNIDAD DE DOMINICA', order: 54 },
  { id: 64, descripcion: 'REINO DE DINAMARCA', order: 55 },
  { id: 65, descripcion: 'REPUBLICA DOMINICANA', order: 56 },
  {
    id: 66,
    descripcion: 'REPUBLICA ARGELINA DEMOCRATICA Y POPULAR',
    order: 57,
  },
  { id: 67, descripcion: 'REPUBLICA ARABE SAHARAUI DEMOCRATICA*', order: 59 },
  { id: 68, descripcion: 'REINO DE ESPAÑA', order: 61 },
  { id: 69, descripcion: 'REPUBLICA DE ESTONIA', order: 62 },
  {
    id: 70,
    descripcion: 'REPUBLICA DEMOCRATICA FEDERAL DE ETIOPIA',
    order: 63,
  },
  { id: 71, descripcion: 'REPUBLICA DE FINLANDIA', order: 64 },
  { id: 72, descripcion: 'REPUBLICA DE FIJI', order: 65 },
  { id: 73, descripcion: 'ISLAS MALVINAS*', order: 66 },
  { id: 74, descripcion: 'REPUBLICA FRANCESA', order: 67 },
  { id: 75, descripcion: 'ISLAS FEROE', order: 68 },
  { id: 76, descripcion: 'ESTADOS FEDERADOS DE MICRONESIA', order: 69 },
  { id: 77, descripcion: 'REPUBLICA GABONESA', order: 70 },
  { id: 84, descripcion: 'GEORGIA', order: 71 },
  { id: 85, descripcion: 'REPUBLICA DE GHANA', order: 72 },
  { id: 86, descripcion: 'GIBRALTAR*', order: 73 },
  { id: 87, descripcion: 'REPUBLICA DE GUINEA', order: 74 },
  { id: 89, descripcion: 'REPUBLICA DE GAMBIA', order: 75 },
  { id: 90, descripcion: 'REPUBLICA DE GUINEA BISSAU', order: 76 },
  { id: 91, descripcion: 'REPUBLICA DE GUINEA ECUATORIAL', order: 77 },
  { id: 92, descripcion: 'REPUBLICA HELENICA', order: 78 },
  { id: 93, descripcion: 'GRANADA', order: 79 },
  { id: 94, descripcion: 'GROENLANDIA', order: 80 },
  { id: 95, descripcion: 'REPUBLICA DE GUATEMALA', order: 81 },
  { id: 97, descripcion: 'GUAM*', order: 82 },
  { id: 98, descripcion: 'REPUBLICA COOPERATIVA DE GUYANA', order: 83 },
  { id: 101, descripcion: 'REPUBLICA DE HONDURAS', order: 84 },
  { id: 102, descripcion: 'REPUBLICA DE CROACIA', order: 85 },
  { id: 103, descripcion: 'REPUBLICA DE HAITI', order: 86 },
  { id: 104, descripcion: 'HUNGRIA', order: 87 },
  { id: 105, descripcion: 'REPUBLICA DE INDONESIA', order: 88 },
  { id: 106, descripcion: 'REPUBLICA DE LA INDIA', order: 89 },
  { id: 108, descripcion: 'REPUBLICA DE IRLANDA', order: 90 },
  { id: 109, descripcion: 'REPUBLICA ISLAMICA DE IRAN', order: 91 },
  { id: 110, descripcion: 'REPUBLICA DE IRAK', order: 92 },
  { id: 111, descripcion: 'REPUBLICA DE ISLANDIA', order: 93 },
  { id: 112, descripcion: 'ESTADO DE ISRAEL', order: 94 },
  { id: 113, descripcion: 'REPUBLICA ITALIANA', order: 95 },
  { id: 114, descripcion: 'JAMAICA', order: 96 },
  { id: 115, descripcion: 'REINO HACHEMITA DE JORDANIA', order: 97 },
  { id: 116, descripcion: 'JAPON', order: 98 },
  { id: 117, descripcion: 'REPUBLICA DE KAZAJSTAN', order: 99 },
  { id: 118, descripcion: 'REPUBLICA DE KENIA', order: 100 },
  { id: 119, descripcion: 'REPUBLICA KIRGUISA', order: 101 },
  { id: 120, descripcion: 'REINO DE CAMBOYA', order: 102 },
  { id: 121, descripcion: 'REPUBLICA DE KIRIBATI', order: 103 },
  { id: 122, descripcion: 'FEDERACION DE SAN CRISTOBAL Y NIEVES', order: 104 },
  { id: 123, descripcion: 'REPUBLICA DE COREA', order: 105 },
  { id: 124, descripcion: 'ESTADO DE KUWAIT', order: 106 },
  { id: 125, descripcion: 'REPUBLICA DEMOCRATICA POPULAR LAO', order: 107 },
  { id: 126, descripcion: 'REPUBLICA LIBANESA', order: 108 },
  { id: 127, descripcion: 'REPUBLICA DE LIBERIA', order: 109 },
  { id: 128, descripcion: 'ESTADO DE LIBIA', order: 110 },
  { id: 129, descripcion: 'SANTA LUCIA', order: 111 },
  { id: 130, descripcion: 'PRINCIPADO DE LIECHTENSTEIN', order: 112 },
  {
    id: 131,
    descripcion: 'REPUBLICA SOCIALISTA DEMOCRATICA DE SRI LANKA',
    order: 113,
  },
  { id: 132, descripcion: 'REINO DE LESOTHO', order: 114 },
  { id: 133, descripcion: 'REPUBLICA DE LITUANIA', order: 115 },
  { id: 134, descripcion: 'GRAN DUCADO DE LUXEMBURGO', order: 116 },
  { id: 135, descripcion: 'REPUBLICA DE LETONIA', order: 117 },
  { id: 137, descripcion: 'REINO DE MARRUECOS', order: 118 },
  { id: 138, descripcion: 'PRINCIPADO DE MONACO', order: 119 },
  { id: 139, descripcion: 'REPUBLICA DE MOLDAVIA', order: 120 },
  { id: 140, descripcion: 'REPUBLICA DE MADAGASCAR', order: 121 },
  { id: 141, descripcion: 'REPUBLICA DE MALDIVAS', order: 122 },
  { id: 142, descripcion: 'MEXICO', order: 1 },
  { id: 143, descripcion: 'REPUBLICA DE LAS ISLAS MARSHALL', order: 123 },
  {
    id: 144,
    descripcion: 'ANTIGUA REPUBLICA YUGOSLAVA DE MACEDONIA',
    order: 124,
  },
  { id: 145, descripcion: 'REPUBLICA DE MALI', order: 125 },
  { id: 146, descripcion: 'REPUBLICA DE MALTA', order: 126 },
  { id: 147, descripcion: 'UNION DE MYANMAR', order: 127 },
  { id: 148, descripcion: 'MONGOLIA', order: 128 },
  {
    id: 149,
    descripcion: 'MANCOMUNIDAD DE LAS ISLAS MARIANAS DEL NORTE',
    order: 129,
  },
  { id: 150, descripcion: 'REPUBLICA DE MOZAMBIQUE', order: 130 },
  { id: 151, descripcion: 'REPUBLICA ISLAMICA DE MAURITANIA', order: 131 },
  { id: 152, descripcion: 'MONTSERRAT*', order: 132 },
  { id: 154, descripcion: 'REPUBLICA DE MAURICIO', order: 133 },
  { id: 155, descripcion: 'REPUBLICA DE MALAUI', order: 134 },
  { id: 156, descripcion: 'MALASIA', order: 135 },
  { id: 157, descripcion: 'REPUBLICA DE NAMIBIA', order: 136 },
  { id: 159, descripcion: 'REPUBLICA DEL NIGER', order: 137 },
  { id: 161, descripcion: 'REPUBLICA FEDERAL DE NIGERIA', order: 138 },
  { id: 162, descripcion: 'REPUBLICA DE NICARAGUA', order: 139 },
  { id: 163, descripcion: 'NIUE', order: 140 },
  { id: 164, descripcion: 'REINO DE LOS PAISES BAJOS', order: 141 },
  { id: 165, descripcion: 'REINO DE NORUEGA', order: 142 },
  {
    id: 166,
    descripcion: 'REPUBLICA FEDERAL DEMOCRATICA DE NEPAL',
    order: 143,
  },
  { id: 167, descripcion: 'REPUBLICA DE NAURU', order: 144 },
  { id: 169, descripcion: 'NUEVA ZELANDIA', order: 145 },
  { id: 170, descripcion: 'SULTANATO DE OMAN', order: 146 },
  { id: 171, descripcion: 'REPUBLICA ISLAMICA DE PAKISTAN', order: 147 },
  { id: 172, descripcion: 'REPUBLICA DE PANAMA', order: 148 },
  {
    id: 173,
    descripcion: 'ISLAS PITCAIRN, HENDERSON, DUCIE Y OENO*',
    order: 149,
  },
  { id: 174, descripcion: 'REPUBLICA DEL PERU', order: 150 },
  { id: 175, descripcion: 'REPUBLICA DE FILIPINAS', order: 151 },
  { id: 176, descripcion: 'REPUBLICA DE PALAOS', order: 152 },
  {
    id: 177,
    descripcion: 'ESTADO INDEPENDIENTE DE PAPUA NUEVA GUINEA',
    order: 153,
  },
  { id: 178, descripcion: 'REPUBLICA DE POLONIA', order: 154 },
  { id: 179, descripcion: 'ESTADO LIBRE ASOCIADO DE PUERTO RICO', order: 155 },
  {
    id: 180,
    descripcion: 'REPUBLICA POPULAR DEMOCRATICA DE COREA',
    order: 156,
  },
  { id: 181, descripcion: 'REPUBLICA PORTUGUESA', order: 157 },
  { id: 182, descripcion: 'REPUBLICA DEL PARAGUAY', order: 158 },
  { id: 184, descripcion: 'ESTADO DE QATAR', order: 159 },
  { id: 186, descripcion: 'RUMANIA', order: 160 },
  { id: 187, descripcion: 'FEDERACION DE RUSIA', order: 161 },
  { id: 188, descripcion: 'REPUBLICA DE RUANDA', order: 162 },
  { id: 189, descripcion: 'REINO DE ARABIA SAUDITA', order: 163 },
  { id: 190, descripcion: 'REPUBLICA DEL SUDAN', order: 164 },
  { id: 191, descripcion: 'REPUBLICA DE SENEGAL', order: 165 },
  { id: 192, descripcion: 'REPUBLICA DE SINGAPUR', order: 166 },
  { id: 193, descripcion: 'ISLA SANTA HELENA*', order: 167 },
  { id: 195, descripcion: 'ISLAS SALOMON', order: 168 },
  { id: 196, descripcion: 'REPUBLICA DE SIERRA LEONA', order: 169 },
  { id: 197, descripcion: 'REPUBLICA DE EL SALVADOR', order: 170 },
  { id: 198, descripcion: 'REPUBLICA DE SAN MARINO', order: 171 },
  { id: 199, descripcion: 'REPUBLICA FEDERAL DE SOMALIA', order: 172 },
  {
    id: 201,
    descripcion: 'REPUBLICA DEMOCRATICA DE SANTO TOME Y PRINCIPE',
    order: 173,
  },
  { id: 202, descripcion: 'REPUBLICA DE SURINAM', order: 174 },
  { id: 203, descripcion: 'REPUBLICA ESLOVACA', order: 175 },
  { id: 204, descripcion: 'REPUBLICA DE ESLOVENIA', order: 176 },
  { id: 205, descripcion: 'REINO DE SUECIA', order: 177 },
  { id: 206, descripcion: 'REINO DE SUAZILANDIA', order: 178 },
  { id: 207, descripcion: 'REPUBLICA DE LAS SEYCHELLES', order: 179 },
  { id: 208, descripcion: 'REPUBLICA ARABE SIRIA', order: 180 },
  { id: 209, descripcion: 'ISLAS TURCAS Y CAICOS*', order: 181 },
  { id: 210, descripcion: 'REPUBLICA DEL CHAD', order: 182 },
  { id: 211, descripcion: 'REPUBLICA TOGOLESA', order: 183 },
  { id: 212, descripcion: 'REINO DE TAILANDIA', order: 184 },
  { id: 213, descripcion: 'REPUBLICA DE TAYIKISTAN', order: 185 },
  { id: 214, descripcion: 'TOKELAU*', order: 186 },
  { id: 215, descripcion: 'TURKMENISTAN', order: 187 },
  {
    id: 216,
    descripcion: 'REPUBLICA DEMOCRATICA DE TIMOR ORIENTAL',
    order: 188,
  },
  { id: 217, descripcion: 'REINO DE TONGA', order: 189 },
  { id: 218, descripcion: 'REPUBLICA DE TRINIDAD Y TOBAGO', order: 190 },
  { id: 219, descripcion: 'REPUBLICA TUNECINA', order: 191 },
  { id: 220, descripcion: 'REPUBLICA DE TURQUIA', order: 192 },
  { id: 221, descripcion: 'TUVALU', order: 193 },
  { id: 222, descripcion: 'TAIWAN', order: 194 },
  { id: 223, descripcion: 'REPUBLICA UNIDA DE TANZANIA', order: 195 },
  { id: 224, descripcion: 'REPUBLICA DE UGANDA', order: 196 },
  { id: 225, descripcion: 'UCRANIA', order: 197 },
  { id: 227, descripcion: 'REPUBLICA ORIENTAL DEL URUGUAY', order: 198 },
  { id: 228, descripcion: 'ESTADOS UNIDOS DE AMERICA', order: 2 },
  { id: 229, descripcion: 'REPUBLICA DE UZBEKISTAN', order: 199 },
  { id: 230, descripcion: 'ESTADO DE LA CIUDAD DEL VATICANO', order: 200 },
  { id: 231, descripcion: 'SAN VICENTE Y LAS GRANADINAS', order: 201 },
  { id: 232, descripcion: 'REPUBLICA BOLIVARIANA DE VENEZUELA', order: 202 },
  { id: 233, descripcion: 'ISLAS VIRGENES BRITANICAS*', order: 203 },
  { id: 234, descripcion: 'ISLAS VIRGENES DE LOS ESTADOS UNIDOS*', order: 204 },
  { id: 235, descripcion: 'REPUBLICA SOCIALISTA DE VIETNAM', order: 205 },
  { id: 236, descripcion: 'REPUBLICA DE VANUATU', order: 206 },
  { id: 238, descripcion: 'ESTADO INDEPENDIENTE DE SAMOA', order: 207 },
  { id: 240, descripcion: 'REPUBLICA DE YEMEN', order: 208 },
  { id: 242, descripcion: 'REPUBLICA DE SUDAFRICA', order: 209 },
  { id: 243, descripcion: 'REPUBLICA DEMOCRATICA DEL CONGO', order: 210 },
  { id: 244, descripcion: 'REPUBLICA DE ZAMBIA', order: 211 },
  { id: 245, descripcion: 'REPUBLICA DE ZIMBABUE', order: 212 },
  { id: 246, descripcion: 'OTRO', order: 213 },
  { id: 247, descripcion: 'SE IGNORA', order: 214 },
  { id: 248, descripcion: 'NO ESPECIFICADO', order: 215 },
  { id: 249, descripcion: 'ESTADO DE ERITREA', order: 216 },
  { id: 250, descripcion: 'REPUBLICA DE SUDAN DEL SUR', order: 217 },
  { id: 251, descripcion: 'CURAZAO', order: 218 },
  { id: 252, descripcion: 'ESTADO DE PALESTINA', order: 219 },
  { id: 253, descripcion: 'ISLA DE MAN', order: 220 },
  { id: 254, descripcion: 'ISLA DE SINT MAARTEN', order: 221 },
  { id: 255, descripcion: 'ISLA WAKE', order: 222 },
  {
    id: 256,
    descripcion: 'REINO UNIDO DE GRAN BRETAÑA E IRLANDA DEL NORTE',
    order: 223,
  },
  { id: 257, descripcion: 'REPUBLICA DE SERBIA', order: 224 },
  { id: 258, descripcion: 'REPUBLICA DE MONTENEGRO', order: 225 },
];

export const SEXO_CATALOG = [
  { id: 0, descripcion: 'NO ESPECIFICADO', order: 0 },
  { id: 1, descripcion: 'HOMBRE', order: 1 },
  { id: 2, descripcion: 'MUJER', order: 2 },
  { id: 3, descripcion: 'INTERSEXUAL', order: 3 },
  { id: 9, descripcion: 'SE IGNORA', order: 9 },
];

export const PRIVILEGIOS_CATALOGO = [
  { id: 1, descripcion: 'REGISTRO DE PACIENTES' },
  { id: 2, descripcion: 'AGENDA DE CITAS' },
  { id: 3, descripcion: 'HISTORIA CLÍNICA' },
  { id: 4, descripcion: 'CONSULTA EXTERNA' },

  { id: 5, descripcion: 'FUSIONAR EXPEDIENTES' },
  { id: 6, descripcion: 'DESCARGA DE DATOS PARA SINBA' },
  { id: 7, descripcion: 'ADMINISTRADOR DE USUARIOS DEL SISTEMA' },
  { id: 8, descripcion: 'ADMINISTRADOR DE DATOS DE LA UNIDAD MÉDICA' },
  { id: 9, descripcion: 'FARMACIA' },
  { id: 10, descripcion: 'ATENCIÓN DE ENFERMERÍA' },
];

export const UNIDAD_MEDICA_CATALOG: UnidadSalud[] = [
  {
    CLUES: 'VZIMB000814',
    CLAVE_DE_LA_INSTITUCION: 'IMB',
    NOMBRE_DE_LA_INSTITUCION: 'SERVICIOS DE SALUD IMSS BIENESTAR',
    CLAVE_DE_LA_ENTIDAD: 30,
    ENTIDAD: 'VERACRUZ DE IGNACIO DE LA LLAVE',
    CLAVE_DEL_MUNICIPIO: 38,
    MUNICIPIO: 'COATEPEC',
    CLAVE_DE_LA_LOCALIDAD: 19,
    LOCALIDAD: 'TUZAMAPAN',
    CLAVE_DE_LA_JURISDICCION: 5,
    JURISDICCION: 'XALAPA',
    CLAVE_DEL_TIPO_ESTABLECIMIENTO: 1,
    NOMBRE_TIPO_ESTABLECIMIENTO: 'DE CONSULTA EXTERNA',
    CLAVE_DE_TIPOLOGIA: 'E',
    NOMBRE_DE_TIPOLOGIA: 'URBANO DE 02 NÚCLEOS BÁSICOS',
    CLAVE_DE_SUBTIPOLOGIA: 99,
    NOMBRE_DE_SUBTIPOLOGIA: 'NO ESPECIFICADO',
    NOMBRE_DE_LA_UNIDAD: 'TUZAMAPAN',
    NOMBRE_COMERCIAL: 'TUZAMAPAN',
    CLAVE_TIPO_DE_VIALIDAD: 5,
    TIPO_DE_VIALIDAD: 'CALLE',
    VIALIDAD: 'J. MA. GOROZPE',
    NUMERO_EXTERIOR: 'SIN NUMERO',
    NUMERO_INTERIOR: 'SIN NÚMERO',
    CLAVE_TIPO_DE_ASENTAMIENTO: 25,
    TIPO_DE_ASENTAMIENTO: 'PUEBLO',
    ASENTAMIENTO: 'TUZAMAPAN',
    CODIGO_POSTAL: '91610',
    OBSERVACIONES_DE_LA_DIRECCION:
      'ENTRE CALLESS ARTÍCULO 123 Y EMILIANO ZAPATA',
    CLAVE_ESTATUS_DE_OPERACION: 1,
    ESTATUS_DE_OPERACION: 'EN OPERACION',
    FECHA_DE_CONSTRUCCION: '10/09/1996',
    FECHA_DE_INICIO_DE_OPERACION: '10/09/1998',
    CLAVE_UNIDAD_MOVIL_MARCA: '',
    UNIDAD_MOVIL_MARCA: '',
    UNIDAD_MOVIL_MARCA_ESPECIFICA: '',
    UNIDAD_MOVIL_MODELO: '',
    CLAVE_UNIDAD_MOVIL_PROGRAMA: '',
    UNIDAD_MOVIL_PROGRAMA: '',
    CLAVE_UNIDAD_MOVIL_TIPO: '',
    UNIDAD_MOVIL_TIPO: '',
    CLAVE_UNIDAD_MOVIL_TIPOLOGIA: '',
    UNIDAD_MOVIL_TIPOLOGIA: '',
    CLAVE_DE_LA_INS_ADM: 'IMB',
    NOMBRE_DE_LA_INS_ADM: 'SERVICIOS DE SALUD IMSS BIENESTAR',
    CLAVE_NIVEL_ATENCION: 1,
    NIVEL_ATENCION: 'PRIMER NIVEL',
    CLAVE_ESTRATO_UNIDAD: 2,
    ESTRATO_UNIDAD: 'URBANO',
    CLAVE_TIPO_OBRA: 5,
    TIPO_OBRA: 'OTRA',
    CLAVE_PROPIEDAD_DEL_INMUEBLE: 5,
    PROPIEDAD_DEL_INMUEBLE: 'OTRO',
    LATITUD: 19.40275,
    LONGITUD: -96.86301,
    CLAVE_ULTIMO_MOVIMIENTO: 'A',
    ULTIMO_MOVIMIENTO: 'ALTA',
    FECHA_ULTIMO_MOVIMIENTO: '18/07/2024',
    COMENTARIOS_DE_LA_VALIDACION:
      'ESTABLECIMIENTO QUE PERTENECÍA A SECRETARIA DE SALUD DEL ESTADO, SE TRANSFIERE A SERVICIOS DE SALUD IMSS BIENESTAR.',
    CLAVE_MOTIVO_BAJA: '',
    MOTIVO_BAJA: '',
    FECHA_EFECTIVA_DE_BAJA: '',
  },
  {
    CLUES: 'VZIMB001695',
    CLAVE_DE_LA_INSTITUCION: 'IMB',
    NOMBRE_DE_LA_INSTITUCION: 'SERVICIOS DE SALUD IMSS BIENESTAR',
    CLAVE_DE_LA_ENTIDAD: 30,
    ENTIDAD: 'VERACRUZ DE IGNACIO DE LA LLAVE',
    CLAVE_DEL_MUNICIPIO: 65,
    MUNICIPIO: 'EMILIANO ZAPATA',
    CLAVE_DE_LA_LOCALIDAD: 1,
    LOCALIDAD: 'DOS RIOS',
    CLAVE_DE_LA_JURISDICCION: 5,
    JURISDICCION: 'XALAPA',
    CLAVE_DEL_TIPO_ESTABLECIMIENTO: 1,
    NOMBRE_TIPO_ESTABLECIMIENTO: 'DE CONSULTA EXTERNA',
    CLAVE_DE_TIPOLOGIA: 'E',
    NOMBRE_DE_TIPOLOGIA: 'URBANO DE 02 NÚCLEOS BÁSICOS',
    CLAVE_DE_SUBTIPOLOGIA: 99,
    NOMBRE_DE_SUBTIPOLOGIA: 'NO ESPECIFICADO',
    NOMBRE_DE_LA_UNIDAD: 'DOS RÍOS',
    NOMBRE_COMERCIAL: 'DOS RÍOS',
    CLAVE_TIPO_DE_VIALIDAD: 5,
    TIPO_DE_VIALIDAD: 'CALLE',
    VIALIDAD: 'ANTONIA DIAZ',
    NUMERO_EXTERIOR: 'SIN NUMERO',
    NUMERO_INTERIOR: 'SIN NÚMERO',
    CLAVE_TIPO_DE_ASENTAMIENTO: 25,
    TIPO_DE_ASENTAMIENTO: 'PUEBLO',
    ASENTAMIENTO: 'DOS RIOS',
    CODIGO_POSTAL: '91640',
    OBSERVACIONES_DE_LA_DIRECCION: 'ANTONIO DIAZ S/N',
    CLAVE_ESTATUS_DE_OPERACION: 1,
    ESTATUS_DE_OPERACION: 'EN OPERACION',
    FECHA_DE_CONSTRUCCION: '10/04/1976',
    FECHA_DE_INICIO_DE_OPERACION: '10/04/1978',
    CLAVE_UNIDAD_MOVIL_MARCA: '',
    UNIDAD_MOVIL_MARCA: '',
    UNIDAD_MOVIL_MARCA_ESPECIFICA: '',
    UNIDAD_MOVIL_MODELO: '',
    CLAVE_UNIDAD_MOVIL_PROGRAMA: '',
    UNIDAD_MOVIL_PROGRAMA: '',
    CLAVE_UNIDAD_MOVIL_TIPO: '',
    UNIDAD_MOVIL_TIPO: '',
    CLAVE_UNIDAD_MOVIL_TIPOLOGIA: '',
    UNIDAD_MOVIL_TIPOLOGIA: '',
    CLAVE_DE_LA_INS_ADM: 'IMB',
    NOMBRE_DE_LA_INS_ADM: 'SERVICIOS DE SALUD IMSS BIENESTAR',
    CLAVE_NIVEL_ATENCION: 1,
    NIVEL_ATENCION: 'PRIMER NIVEL',
    CLAVE_ESTRATO_UNIDAD: 2,
    ESTRATO_UNIDAD: 'URBANO',
    CLAVE_TIPO_OBRA: 5,
    TIPO_OBRA: 'OTRA',
    CLAVE_PROPIEDAD_DEL_INMUEBLE: 5,
    PROPIEDAD_DEL_INMUEBLE: 'OTRO',
    LATITUD: 19.48024,
    LONGITUD: -96.7975,
    CLAVE_ULTIMO_MOVIMIENTO: 'A',
    ULTIMO_MOVIMIENTO: 'ALTA',
    FECHA_ULTIMO_MOVIMIENTO: '18/07/2024',
    COMENTARIOS_DE_LA_VALIDACION:
      'ESTABLECIMIENTO QUE PERTENECÍA A SECRETARIA DE SALUD DEL ESTADO, SE TRANSFIERE A SERVICIOS DE SALUD IMSS BIENESTAR.',
    CLAVE_MOTIVO_BAJA: '',
    MOTIVO_BAJA: '',
    FECHA_EFECTIVA_DE_BAJA: '',
  },
  {
    CLUES: 'VZIMB001700',
    CLAVE_DE_LA_INSTITUCION: 'IMB',
    NOMBRE_DE_LA_INSTITUCION: 'SERVICIOS DE SALUD IMSS BIENESTAR',
    CLAVE_DE_LA_ENTIDAD: 30,
    ENTIDAD: 'VERACRUZ DE IGNACIO DE LA LLAVE',
    CLAVE_DEL_MUNICIPIO: 65,
    MUNICIPIO: 'EMILIANO ZAPATA',
    CLAVE_DE_LA_LOCALIDAD: 12,
    LOCALIDAD: 'EL CHICO',
    CLAVE_DE_LA_JURISDICCION: 5,
    JURISDICCION: 'XALAPA',
    CLAVE_DEL_TIPO_ESTABLECIMIENTO: 1,
    NOMBRE_TIPO_ESTABLECIMIENTO: 'DE CONSULTA EXTERNA',
    CLAVE_DE_TIPOLOGIA: 'B',
    NOMBRE_DE_TIPOLOGIA: 'RURAL DE 02 NÚCLEOS BÁSICOS',
    CLAVE_DE_SUBTIPOLOGIA: 99,
    NOMBRE_DE_SUBTIPOLOGIA: 'NO ESPECIFICADO',
    NOMBRE_DE_LA_UNIDAD: 'EL CHICO',
    NOMBRE_COMERCIAL: 'EL CHICO',
    CLAVE_TIPO_DE_VIALIDAD: 5,
    TIPO_DE_VIALIDAD: 'CALLE',
    VIALIDAD: 'HIDALGO',
    NUMERO_EXTERIOR: 'SIN NUMERO',
    NUMERO_INTERIOR: 'SIN NÚMERO',
    CLAVE_TIPO_DE_ASENTAMIENTO: 25,
    TIPO_DE_ASENTAMIENTO: 'PUEBLO',
    ASENTAMIENTO: 'EL CHICO',
    CODIGO_POSTAL: '91637',
    OBSERVACIONES_DE_LA_DIRECCION: 'HIDALGO ESQ. LOS PINOS S/N',
    CLAVE_ESTATUS_DE_OPERACION: 1,
    ESTATUS_DE_OPERACION: 'EN OPERACION',
    FECHA_DE_CONSTRUCCION: '10/11/1996',
    FECHA_DE_INICIO_DE_OPERACION: '10/11/1998',
    CLAVE_UNIDAD_MOVIL_MARCA: '',
    UNIDAD_MOVIL_MARCA: '',
    UNIDAD_MOVIL_MARCA_ESPECIFICA: '',
    UNIDAD_MOVIL_MODELO: '',
    CLAVE_UNIDAD_MOVIL_PROGRAMA: '',
    UNIDAD_MOVIL_PROGRAMA: '',
    CLAVE_UNIDAD_MOVIL_TIPO: '',
    UNIDAD_MOVIL_TIPO: '',
    CLAVE_UNIDAD_MOVIL_TIPOLOGIA: '',
    UNIDAD_MOVIL_TIPOLOGIA: '',
    CLAVE_DE_LA_INS_ADM: 'IMB',
    NOMBRE_DE_LA_INS_ADM: 'SERVICIOS DE SALUD IMSS BIENESTAR',
    CLAVE_NIVEL_ATENCION: 1,
    NIVEL_ATENCION: 'PRIMER NIVEL',
    CLAVE_ESTRATO_UNIDAD: 1,
    ESTRATO_UNIDAD: 'RURAL',
    CLAVE_TIPO_OBRA: 5,
    TIPO_OBRA: 'OTRA',
    CLAVE_PROPIEDAD_DEL_INMUEBLE: 5,
    PROPIEDAD_DEL_INMUEBLE: 'OTRO',
    LATITUD: 19.464801,
    LONGITUD: -96.83801,
    CLAVE_ULTIMO_MOVIMIENTO: 'A',
    ULTIMO_MOVIMIENTO: 'ALTA',
    FECHA_ULTIMO_MOVIMIENTO: '18/07/2024',
    COMENTARIOS_DE_LA_VALIDACION:
      'ESTABLECIMIENTO QUE PERTENECÍA A SECRETARIA DE SALUD DEL ESTADO, SE TRANSFIERE A SERVICIOS DE SALUD IMSS BIENESTAR.',
    CLAVE_MOTIVO_BAJA: '',
    MOTIVO_BAJA: '',
    FECHA_EFECTIVA_DE_BAJA: '',
  },
  {
    CLUES: 'VZIMB003795',
    CLAVE_DE_LA_INSTITUCION: 'IMB',
    NOMBRE_DE_LA_INSTITUCION: 'SERVICIOS DE SALUD IMSS BIENESTAR',
    CLAVE_DE_LA_ENTIDAD: 30,
    ENTIDAD: 'VERACRUZ DE IGNACIO DE LA LLAVE',
    CLAVE_DEL_MUNICIPIO: 132,
    MUNICIPIO: 'LAS VIGAS DE RAMIREZ',
    CLAVE_DE_LA_LOCALIDAD: 1,
    LOCALIDAD: 'LAS VIGAS DE RAMIREZ',
    CLAVE_DE_LA_JURISDICCION: 5,
    JURISDICCION: 'XALAPA',
    CLAVE_DEL_TIPO_ESTABLECIMIENTO: 1,
    NOMBRE_TIPO_ESTABLECIMIENTO: 'DE CONSULTA EXTERNA',
    CLAVE_DE_TIPOLOGIA: 'G',
    NOMBRE_DE_TIPOLOGIA: 'URBANO DE 04 NÚCLEOS BÁSICOS',
    CLAVE_DE_SUBTIPOLOGIA: 99,
    NOMBRE_DE_SUBTIPOLOGIA: 'NO ESPECIFICADO',
    NOMBRE_DE_LA_UNIDAD: 'LAS VIGAS DE RAMÍREZ',
    NOMBRE_COMERCIAL: 'LAS VIGAS DE RAMÍREZ',
    CLAVE_TIPO_DE_VIALIDAD: 3,
    TIPO_DE_VIALIDAD: 'AVENIDA',
    VIALIDAD: 'HIDALGO NORTE',
    NUMERO_EXTERIOR: '1',
    NUMERO_INTERIOR: 'SIN NÚMERO',
    CLAVE_TIPO_DE_ASENTAMIENTO: 25,
    TIPO_DE_ASENTAMIENTO: 'PUEBLO',
    ASENTAMIENTO: 'LAS VIGAS DE RAMIREZ',
    CODIGO_POSTAL: '91330',
    OBSERVACIONES_DE_LA_DIRECCION: 'ENTRE CALLES ITURBIDE Y CARRETERA NACIONAL',
    CLAVE_ESTATUS_DE_OPERACION: 1,
    ESTATUS_DE_OPERACION: 'EN OPERACION',
    FECHA_DE_CONSTRUCCION: '01/07/1963',
    FECHA_DE_INICIO_DE_OPERACION: '30/06/1965',
    CLAVE_UNIDAD_MOVIL_MARCA: '',
    UNIDAD_MOVIL_MARCA: '',
    UNIDAD_MOVIL_MARCA_ESPECIFICA: '',
    UNIDAD_MOVIL_MODELO: '',
    CLAVE_UNIDAD_MOVIL_PROGRAMA: '',
    UNIDAD_MOVIL_PROGRAMA: '',
    CLAVE_UNIDAD_MOVIL_TIPO: '',
    UNIDAD_MOVIL_TIPO: '',
    CLAVE_UNIDAD_MOVIL_TIPOLOGIA: '',
    UNIDAD_MOVIL_TIPOLOGIA: '',
    CLAVE_DE_LA_INS_ADM: 'IMB',
    NOMBRE_DE_LA_INS_ADM: 'SERVICIOS DE SALUD IMSS BIENESTAR',
    CLAVE_NIVEL_ATENCION: 1,
    NIVEL_ATENCION: 'PRIMER NIVEL',
    CLAVE_ESTRATO_UNIDAD: 2,
    ESTRATO_UNIDAD: 'URBANO',
    CLAVE_TIPO_OBRA: 5,
    TIPO_OBRA: 'OTRA',
    CLAVE_PROPIEDAD_DEL_INMUEBLE: 5,
    PROPIEDAD_DEL_INMUEBLE: 'OTRO',
    LATITUD: 19.637501,
    LONGITUD: -97.0934,
    CLAVE_ULTIMO_MOVIMIENTO: 'A',
    ULTIMO_MOVIMIENTO: 'ALTA',
    FECHA_ULTIMO_MOVIMIENTO: '18/07/2024',
    COMENTARIOS_DE_LA_VALIDACION:
      'ESTABLECIMIENTO QUE PERTENECÍA A SECRETARIA DE SALUD DEL ESTADO, SE TRANSFIERE A SERVICIOS DE SALUD IMSS BIENESTAR.',
    CLAVE_MOTIVO_BAJA: '',
    MOTIVO_BAJA: '',
    FECHA_EFECTIVA_DE_BAJA: '',
  },
  {
    CLUES: 'VZIMB003865',
    CLAVE_DE_LA_INSTITUCION: 'IMB',
    NOMBRE_DE_LA_INSTITUCION: 'SERVICIOS DE SALUD IMSS BIENESTAR',
    CLAVE_DE_LA_ENTIDAD: 30,
    ENTIDAD: 'VERACRUZ DE IGNACIO DE LA LLAVE',
    CLAVE_DEL_MUNICIPIO: 136,
    MUNICIPIO: 'RAFAEL LUCIO',
    CLAVE_DE_LA_LOCALIDAD: 1,
    LOCALIDAD: 'RAFAEL LUCIO',
    CLAVE_DE_LA_JURISDICCION: 5,
    JURISDICCION: 'XALAPA',
    CLAVE_DEL_TIPO_ESTABLECIMIENTO: 1,
    NOMBRE_TIPO_ESTABLECIMIENTO: 'DE CONSULTA EXTERNA',
    CLAVE_DE_TIPOLOGIA: 'E',
    NOMBRE_DE_TIPOLOGIA: 'URBANO DE 02 NÚCLEOS BÁSICOS',
    CLAVE_DE_SUBTIPOLOGIA: 99,
    NOMBRE_DE_SUBTIPOLOGIA: 'NO ESPECIFICADO',
    NOMBRE_DE_LA_UNIDAD: 'RAFAEL LUCIO',
    NOMBRE_COMERCIAL: 'RAFAEL LUCIO',
    CLAVE_TIPO_DE_VIALIDAD: 5,
    TIPO_DE_VIALIDAD: 'CALLE',
    VIALIDAD: 'ALVARO OBREGON',
    NUMERO_EXTERIOR: '29',
    NUMERO_INTERIOR: 'SIN NÚMERO',
    CLAVE_TIPO_DE_ASENTAMIENTO: 25,
    TIPO_DE_ASENTAMIENTO: 'PUEBLO',
    ASENTAMIENTO: 'RAFAEL LUCIO',
    CODIGO_POSTAL: '91315',
    OBSERVACIONES_DE_LA_DIRECCION:
      'ARRIBA DE LA CASA DEL ABUELO, ENTRE CALLES FRANCISCO I. MADERO Y AQUILES SERDÁN',
    CLAVE_ESTATUS_DE_OPERACION: 1,
    ESTATUS_DE_OPERACION: 'EN OPERACION',
    FECHA_DE_CONSTRUCCION: '10/06/1976',
    FECHA_DE_INICIO_DE_OPERACION: '10/06/1978',
    CLAVE_UNIDAD_MOVIL_MARCA: '',
    UNIDAD_MOVIL_MARCA: '',
    UNIDAD_MOVIL_MARCA_ESPECIFICA: '',
    UNIDAD_MOVIL_MODELO: '',
    CLAVE_UNIDAD_MOVIL_PROGRAMA: '',
    UNIDAD_MOVIL_PROGRAMA: '',
    CLAVE_UNIDAD_MOVIL_TIPO: '',
    UNIDAD_MOVIL_TIPO: '',
    CLAVE_UNIDAD_MOVIL_TIPOLOGIA: '',
    UNIDAD_MOVIL_TIPOLOGIA: '',
    CLAVE_DE_LA_INS_ADM: 'IMB',
    NOMBRE_DE_LA_INS_ADM: 'SERVICIOS DE SALUD IMSS BIENESTAR',
    CLAVE_NIVEL_ATENCION: 1,
    NIVEL_ATENCION: 'PRIMER NIVEL',
    CLAVE_ESTRATO_UNIDAD: 2,
    ESTRATO_UNIDAD: 'URBANO',
    CLAVE_TIPO_OBRA: 5,
    TIPO_OBRA: 'OTRA',
    CLAVE_PROPIEDAD_DEL_INMUEBLE: 5,
    PROPIEDAD_DEL_INMUEBLE: 'OTRO',
    LATITUD: 19.5929907,
    LONGITUD: -96.9907737,
    CLAVE_ULTIMO_MOVIMIENTO: 'A',
    ULTIMO_MOVIMIENTO: 'ALTA',
    FECHA_ULTIMO_MOVIMIENTO: '18/07/2024',
    COMENTARIOS_DE_LA_VALIDACION:
      'ESTABLECIMIENTO QUE PERTENECÍA A SECRETARIA DE SALUD DEL ESTADO, SE TRANSFIERE A SERVICIOS DE SALUD IMSS BIENESTAR.',
    CLAVE_MOTIVO_BAJA: '',
    MOTIVO_BAJA: '',
    FECHA_EFECTIVA_DE_BAJA: '',
  },
  {
    CLUES: 'VZIMB004454',
    CLAVE_DE_LA_INSTITUCION: 'IMB',
    NOMBRE_DE_LA_INSTITUCION: 'SERVICIOS DE SALUD IMSS BIENESTAR',
    CLAVE_DE_LA_ENTIDAD: 30,
    ENTIDAD: 'VERACRUZ DE IGNACIO DE LA LLAVE',
    CLAVE_DEL_MUNICIPIO: 156,
    MUNICIPIO: 'TATATILA',
    CLAVE_DE_LA_LOCALIDAD: 1,
    LOCALIDAD: 'TATATILA',
    CLAVE_DE_LA_JURISDICCION: 5,
    JURISDICCION: 'XALAPA',
    CLAVE_DEL_TIPO_ESTABLECIMIENTO: 1,
    NOMBRE_TIPO_ESTABLECIMIENTO: 'DE CONSULTA EXTERNA',
    CLAVE_DE_TIPOLOGIA: 'D',
    NOMBRE_DE_TIPOLOGIA: 'URBANO DE 01 NÚCLEOS BÁSICOS',
    CLAVE_DE_SUBTIPOLOGIA: 99,
    NOMBRE_DE_SUBTIPOLOGIA: 'NO ESPECIFICADO',
    NOMBRE_DE_LA_UNIDAD: 'TATATILA',
    NOMBRE_COMERCIAL: 'TATATILA',
    CLAVE_TIPO_DE_VIALIDAD: 5,
    TIPO_DE_VIALIDAD: 'CALLE',
    VIALIDAD: 'MIGUEL HIDALGO',
    NUMERO_EXTERIOR: 'SIN NUMERO',
    NUMERO_INTERIOR: 'SIN NÚMERO',
    CLAVE_TIPO_DE_ASENTAMIENTO: 27,
    TIPO_DE_ASENTAMIENTO: 'RANCHERÍA',
    ASENTAMIENTO: 'TATATILA',
    CODIGO_POSTAL: '93760',
    OBSERVACIONES_DE_LA_DIRECCION:
      'ENTRE CALLES LERDO DE TEJADA Y JUVENTINO ROSAS',
    CLAVE_ESTATUS_DE_OPERACION: 1,
    ESTATUS_DE_OPERACION: 'EN OPERACION',
    FECHA_DE_CONSTRUCCION: '01/04/1976',
    FECHA_DE_INICIO_DE_OPERACION: '01/04/1978',
    CLAVE_UNIDAD_MOVIL_MARCA: '',
    UNIDAD_MOVIL_MARCA: '',
    UNIDAD_MOVIL_MARCA_ESPECIFICA: '',
    UNIDAD_MOVIL_MODELO: '',
    CLAVE_UNIDAD_MOVIL_PROGRAMA: '',
    UNIDAD_MOVIL_PROGRAMA: '',
    CLAVE_UNIDAD_MOVIL_TIPO: '',
    UNIDAD_MOVIL_TIPO: '',
    CLAVE_UNIDAD_MOVIL_TIPOLOGIA: '',
    UNIDAD_MOVIL_TIPOLOGIA: '',
    CLAVE_DE_LA_INS_ADM: 'IMB',
    NOMBRE_DE_LA_INS_ADM: 'SERVICIOS DE SALUD IMSS BIENESTAR',
    CLAVE_NIVEL_ATENCION: 1,
    NIVEL_ATENCION: 'PRIMER NIVEL',
    CLAVE_ESTRATO_UNIDAD: 2,
    ESTRATO_UNIDAD: 'URBANO',
    CLAVE_TIPO_OBRA: 5,
    TIPO_OBRA: 'OTRA',
    CLAVE_PROPIEDAD_DEL_INMUEBLE: 5,
    PROPIEDAD_DEL_INMUEBLE: 'OTRO',
    LATITUD: 19.69241,
    LONGITUD: -97.1111,
    CLAVE_ULTIMO_MOVIMIENTO: 'A',
    ULTIMO_MOVIMIENTO: 'ALTA',
    FECHA_ULTIMO_MOVIMIENTO: '18/07/2024',
    COMENTARIOS_DE_LA_VALIDACION:
      'ESTABLECIMIENTO QUE PERTENECÍA A SECRETARIA DE SALUD DEL ESTADO, SE TRANSFIERE A SERVICIOS DE SALUD IMSS BIENESTAR.',
    CLAVE_MOTIVO_BAJA: '',
    MOTIVO_BAJA: '',
    FECHA_EFECTIVA_DE_BAJA: '',
  },
  {
    CLUES: 'VZIMB004775',
    CLAVE_DE_LA_INSTITUCION: 'IMB',
    NOMBRE_DE_LA_INSTITUCION: 'SERVICIOS DE SALUD IMSS BIENESTAR',
    CLAVE_DE_LA_ENTIDAD: 30,
    ENTIDAD: 'VERACRUZ DE IGNACIO DE LA LLAVE',
    CLAVE_DEL_MUNICIPIO: 164,
    MUNICIPIO: 'TEOCELO',
    CLAVE_DE_LA_LOCALIDAD: 1,
    LOCALIDAD: 'TEOCELO',
    CLAVE_DE_LA_JURISDICCION: 5,
    JURISDICCION: 'XALAPA',
    CLAVE_DEL_TIPO_ESTABLECIMIENTO: 2,
    NOMBRE_TIPO_ESTABLECIMIENTO: 'DE HOSPITALIZACIÓN',
    CLAVE_DE_TIPOLOGIA: 'N',
    NOMBRE_DE_TIPOLOGIA: 'HOSPITAL INTEGRAL (COMUNITARIO)',
    CLAVE_DE_SUBTIPOLOGIA: 99,
    NOMBRE_DE_SUBTIPOLOGIA: 'NO ESPECIFICADO',
    NOMBRE_DE_LA_UNIDAD: 'HOSPITAL DE LA COMUNIDAD DE TEOCELO',
    NOMBRE_COMERCIAL: 'HOSPITAL DE LA COMUNIDAD DE TEOCELO',
    CLAVE_TIPO_DE_VIALIDAD: 5,
    TIPO_DE_VIALIDAD: 'CALLE',
    VIALIDAD: 'COVARRUBIAS',
    NUMERO_EXTERIOR: '2',
    NUMERO_INTERIOR: 'SIN NÚMERO',
    CLAVE_TIPO_DE_ASENTAMIENTO: 7,
    TIPO_DE_ASENTAMIENTO: 'COLONIA',
    ASENTAMIENTO: 'CENTRO',
    CODIGO_POSTAL: '91615',
    OBSERVACIONES_DE_LA_DIRECCION:
      'ENTRE CALLES AVENIDA INDEPENDENCIA PONIENTE Y CALLE BELISARIO DOMINGUEZ',
    CLAVE_ESTATUS_DE_OPERACION: 1,
    ESTATUS_DE_OPERACION: 'EN OPERACION',
    FECHA_DE_CONSTRUCCION: '30/12/1960',
    FECHA_DE_INICIO_DE_OPERACION: '30/12/1962',
    CLAVE_UNIDAD_MOVIL_MARCA: '',
    UNIDAD_MOVIL_MARCA: '',
    UNIDAD_MOVIL_MARCA_ESPECIFICA: '',
    UNIDAD_MOVIL_MODELO: '',
    CLAVE_UNIDAD_MOVIL_PROGRAMA: '',
    UNIDAD_MOVIL_PROGRAMA: '',
    CLAVE_UNIDAD_MOVIL_TIPO: '',
    UNIDAD_MOVIL_TIPO: '',
    CLAVE_UNIDAD_MOVIL_TIPOLOGIA: '',
    UNIDAD_MOVIL_TIPOLOGIA: '',
    CLAVE_DE_LA_INS_ADM: 'IMB',
    NOMBRE_DE_LA_INS_ADM: 'SERVICIOS DE SALUD IMSS BIENESTAR',
    CLAVE_NIVEL_ATENCION: 2,
    NIVEL_ATENCION: 'SEGUNDO NIVEL',
    CLAVE_ESTRATO_UNIDAD: 2,
    ESTRATO_UNIDAD: 'URBANO',
    CLAVE_TIPO_OBRA: 5,
    TIPO_OBRA: 'OTRA',
    CLAVE_PROPIEDAD_DEL_INMUEBLE: 5,
    PROPIEDAD_DEL_INMUEBLE: 'OTRO',
    LATITUD: 19.38645,
    LONGITUD: -96.9732,
    CLAVE_ULTIMO_MOVIMIENTO: 'A',
    ULTIMO_MOVIMIENTO: 'ALTA',
    FECHA_ULTIMO_MOVIMIENTO: '18/07/2024',
    COMENTARIOS_DE_LA_VALIDACION:
      'ESTABLECIMIENTO QUE PERTENECÍA A SECRETARIA DE SALUD DEL ESTADO, SE TRANSFIERE A SERVICIOS DE SALUD IMSS BIENESTAR.',
    CLAVE_MOTIVO_BAJA: '',
    MOTIVO_BAJA: '',
    FECHA_EFECTIVA_DE_BAJA: '',
  },
  {
    CLUES: 'VZIMB005364',
    CLAVE_DE_LA_INSTITUCION: 'IMB',
    NOMBRE_DE_LA_INSTITUCION: 'SERVICIOS DE SALUD IMSS BIENESTAR',
    CLAVE_DE_LA_ENTIDAD: 30,
    ENTIDAD: 'VERACRUZ DE IGNACIO DE LA LLAVE',
    CLAVE_DEL_MUNICIPIO: 187,
    MUNICIPIO: 'TONAYAN',
    CLAVE_DE_LA_LOCALIDAD: 1,
    LOCALIDAD: 'TONAYAN',
    CLAVE_DE_LA_JURISDICCION: 5,
    JURISDICCION: 'XALAPA',
    CLAVE_DEL_TIPO_ESTABLECIMIENTO: 1,
    NOMBRE_TIPO_ESTABLECIMIENTO: 'DE CONSULTA EXTERNA',
    CLAVE_DE_TIPOLOGIA: 'E',
    NOMBRE_DE_TIPOLOGIA: 'URBANO DE 02 NÚCLEOS BÁSICOS',
    CLAVE_DE_SUBTIPOLOGIA: 99,
    NOMBRE_DE_SUBTIPOLOGIA: 'NO ESPECIFICADO',
    NOMBRE_DE_LA_UNIDAD: 'TONAYAN',
    NOMBRE_COMERCIAL: 'TONAYAN',
    CLAVE_TIPO_DE_VIALIDAD: 5,
    TIPO_DE_VIALIDAD: 'CALLE',
    VIALIDAD: 'ENRIQUEZ',
    NUMERO_EXTERIOR: '3',
    NUMERO_INTERIOR: 'SIN NÚMERO',
    CLAVE_TIPO_DE_ASENTAMIENTO: 13,
    TIPO_DE_ASENTAMIENTO: 'EJIDO',
    ASENTAMIENTO: 'TONAYAN',
    CODIGO_POSTAL: '91360',
    OBSERVACIONES_DE_LA_DIRECCION:
      'ENTRE CALLES FRANCISCO I MADERO Y PINO SUAREZ',
    CLAVE_ESTATUS_DE_OPERACION: 1,
    ESTATUS_DE_OPERACION: 'EN OPERACION',
    FECHA_DE_CONSTRUCCION: '01/02/1977',
    FECHA_DE_INICIO_DE_OPERACION: '01/02/1979',
    CLAVE_UNIDAD_MOVIL_MARCA: '',
    UNIDAD_MOVIL_MARCA: '',
    UNIDAD_MOVIL_MARCA_ESPECIFICA: '',
    UNIDAD_MOVIL_MODELO: '',
    CLAVE_UNIDAD_MOVIL_PROGRAMA: '',
    UNIDAD_MOVIL_PROGRAMA: '',
    CLAVE_UNIDAD_MOVIL_TIPO: '',
    UNIDAD_MOVIL_TIPO: '',
    CLAVE_UNIDAD_MOVIL_TIPOLOGIA: '',
    UNIDAD_MOVIL_TIPOLOGIA: '',
    CLAVE_DE_LA_INS_ADM: 'IMB',
    NOMBRE_DE_LA_INS_ADM: 'SERVICIOS DE SALUD IMSS BIENESTAR',
    CLAVE_NIVEL_ATENCION: 1,
    NIVEL_ATENCION: 'PRIMER NIVEL',
    CLAVE_ESTRATO_UNIDAD: 2,
    ESTRATO_UNIDAD: 'URBANO',
    CLAVE_TIPO_OBRA: 5,
    TIPO_OBRA: 'OTRA',
    CLAVE_PROPIEDAD_DEL_INMUEBLE: 5,
    PROPIEDAD_DEL_INMUEBLE: 'OTRO',
    LATITUD: 19.683058,
    LONGITUD: -96.9217948,
    CLAVE_ULTIMO_MOVIMIENTO: 'A',
    ULTIMO_MOVIMIENTO: 'ALTA',
    FECHA_ULTIMO_MOVIMIENTO: '18/07/2024',
    COMENTARIOS_DE_LA_VALIDACION:
      'ESTABLECIMIENTO QUE PERTENECÍA A SECRETARIA DE SALUD DEL ESTADO, SE TRANSFIERE A SERVICIOS DE SALUD IMSS BIENESTAR.',
    CLAVE_MOTIVO_BAJA: '',
    MOTIVO_BAJA: '',
    FECHA_EFECTIVA_DE_BAJA: '',
  },
  {
    CLUES: 'VZIMB006501',
    CLAVE_DE_LA_INSTITUCION: 'IMB',
    NOMBRE_DE_LA_INSTITUCION: 'SERVICIOS DE SALUD IMSS BIENESTAR',
    CLAVE_DE_LA_ENTIDAD: 30,
    ENTIDAD: 'VERACRUZ DE IGNACIO DE LA LLAVE',
    CLAVE_DEL_MUNICIPIO: 1,
    MUNICIPIO: 'ACAJETE',
    CLAVE_DE_LA_LOCALIDAD: 1,
    LOCALIDAD: 'ACAJETE',
    CLAVE_DE_LA_JURISDICCION: 5,
    JURISDICCION: 'XALAPA',
    CLAVE_DEL_TIPO_ESTABLECIMIENTO: 1,
    NOMBRE_TIPO_ESTABLECIMIENTO: 'DE CONSULTA EXTERNA',
    CLAVE_DE_TIPOLOGIA: 'E',
    NOMBRE_DE_TIPOLOGIA: 'URBANO DE 02 NÚCLEOS BÁSICOS',
    CLAVE_DE_SUBTIPOLOGIA: 99,
    NOMBRE_DE_SUBTIPOLOGIA: 'NO ESPECIFICADO',
    NOMBRE_DE_LA_UNIDAD: 'CENTRO DE SALUD ACAJETE',
    NOMBRE_COMERCIAL: 'CENTRO DE SALUD ACAJETE',
    CLAVE_TIPO_DE_VIALIDAD: 5,
    TIPO_DE_VIALIDAD: 'CALLE',
    VIALIDAD: 'MIGUEL HIDALGO',
    NUMERO_EXTERIOR: 'SIN NUMERO',
    NUMERO_INTERIOR: 'SIN NÚMERO',
    CLAVE_TIPO_DE_ASENTAMIENTO: 25,
    TIPO_DE_ASENTAMIENTO: 'PUEBLO',
    ASENTAMIENTO: 'ACAJETE',
    CODIGO_POSTAL: '91320',
    OBSERVACIONES_DE_LA_DIRECCION: 'CARRETERA FEDERAL MEXICO - VERACRUZ',
    CLAVE_ESTATUS_DE_OPERACION: 1,
    ESTATUS_DE_OPERACION: 'EN OPERACION',
    FECHA_DE_CONSTRUCCION: '23/09/2017',
    FECHA_DE_INICIO_DE_OPERACION: '23/09/2019',
    CLAVE_UNIDAD_MOVIL_MARCA: '',
    UNIDAD_MOVIL_MARCA: '',
    UNIDAD_MOVIL_MARCA_ESPECIFICA: '',
    UNIDAD_MOVIL_MODELO: '',
    CLAVE_UNIDAD_MOVIL_PROGRAMA: '',
    UNIDAD_MOVIL_PROGRAMA: '',
    CLAVE_UNIDAD_MOVIL_TIPO: '',
    UNIDAD_MOVIL_TIPO: '',
    CLAVE_UNIDAD_MOVIL_TIPOLOGIA: '',
    UNIDAD_MOVIL_TIPOLOGIA: '',
    CLAVE_DE_LA_INS_ADM: 'IMB',
    NOMBRE_DE_LA_INS_ADM: 'SERVICIOS DE SALUD IMSS BIENESTAR',
    CLAVE_NIVEL_ATENCION: 1,
    NIVEL_ATENCION: 'PRIMER NIVEL',
    CLAVE_ESTRATO_UNIDAD: 2,
    ESTRATO_UNIDAD: 'URBANO',
    CLAVE_TIPO_OBRA: 5,
    TIPO_OBRA: 'OTRA',
    CLAVE_PROPIEDAD_DEL_INMUEBLE: 1,
    PROPIEDAD_DEL_INMUEBLE: 'PROPIO',
    LATITUD: 19.584118,
    LONGITUD: -97.013837,
    CLAVE_ULTIMO_MOVIMIENTO: 'A',
    ULTIMO_MOVIMIENTO: 'ALTA',
    FECHA_ULTIMO_MOVIMIENTO: '18/07/2024',
    COMENTARIOS_DE_LA_VALIDACION:
      'ESTABLECIMIENTO QUE PERTENECÍA A SECRETARIA DE SALUD DEL ESTADO, SE TRANSFIERE A SERVICIOS DE SALUD IMSS BIENESTAR.',
    CLAVE_MOTIVO_BAJA: '',
    MOTIVO_BAJA: '',
    FECHA_EFECTIVA_DE_BAJA: '',
  },
  {
    CLUES: 'VZIMB007102',
    CLAVE_DE_LA_INSTITUCION: 'IMB',
    NOMBRE_DE_LA_INSTITUCION: 'SERVICIOS DE SALUD IMSS BIENESTAR',
    CLAVE_DE_LA_ENTIDAD: 30,
    ENTIDAD: 'VERACRUZ DE IGNACIO DE LA LLAVE',
    CLAVE_DEL_MUNICIPIO: 128,
    MUNICIPIO: 'PEROTE',
    CLAVE_DE_LA_LOCALIDAD: 1,
    LOCALIDAD: 'PEROTE',
    CLAVE_DE_LA_JURISDICCION: 5,
    JURISDICCION: 'XALAPA',
    CLAVE_DEL_TIPO_ESTABLECIMIENTO: 2,
    NOMBRE_TIPO_ESTABLECIMIENTO: 'DE HOSPITALIZACIÓN',
    CLAVE_DE_TIPOLOGIA: 'M',
    NOMBRE_DE_TIPOLOGIA: 'HOSPITAL GENERAL',
    CLAVE_DE_SUBTIPOLOGIA: 99,
    NOMBRE_DE_SUBTIPOLOGIA: 'NO ESPECIFICADO',
    NOMBRE_DE_LA_UNIDAD: 'HOSPITAL GENERAL PEROTE VERACRUZ',
    NOMBRE_COMERCIAL: 'HOSPITAL GENERAL PEROTE VERACRUZ',
    CLAVE_TIPO_DE_VIALIDAD: 5,
    TIPO_DE_VIALIDAD: 'CALLE',
    VIALIDAD: 'PENSAMIENTO',
    NUMERO_EXTERIOR: '28',
    NUMERO_INTERIOR: 'N/A',
    CLAVE_TIPO_DE_ASENTAMIENTO: 7,
    TIPO_DE_ASENTAMIENTO: 'COLONIA',
    ASENTAMIENTO: 'JARDÍNES DE SAN CARLOS',
    CODIGO_POSTAL: '91273',
    OBSERVACIONES_DE_LA_DIRECCION: 'A 500 METROS DE LA FORTALEZA DE SAN CARLOS',
    CLAVE_ESTATUS_DE_OPERACION: 1,
    ESTATUS_DE_OPERACION: 'EN OPERACION',
    FECHA_DE_CONSTRUCCION: '17/05/2021',
    FECHA_DE_INICIO_DE_OPERACION: '20/07/2022',
    CLAVE_UNIDAD_MOVIL_MARCA: '',
    UNIDAD_MOVIL_MARCA: '',
    UNIDAD_MOVIL_MARCA_ESPECIFICA: '',
    UNIDAD_MOVIL_MODELO: '',
    CLAVE_UNIDAD_MOVIL_PROGRAMA: '',
    UNIDAD_MOVIL_PROGRAMA: '',
    CLAVE_UNIDAD_MOVIL_TIPO: '',
    UNIDAD_MOVIL_TIPO: '',
    CLAVE_UNIDAD_MOVIL_TIPOLOGIA: '',
    UNIDAD_MOVIL_TIPOLOGIA: '',
    CLAVE_DE_LA_INS_ADM: 'IMB',
    NOMBRE_DE_LA_INS_ADM: 'SERVICIOS DE SALUD IMSS BIENESTAR',
    CLAVE_NIVEL_ATENCION: 2,
    NIVEL_ATENCION: 'SEGUNDO NIVEL',
    CLAVE_ESTRATO_UNIDAD: 2,
    ESTRATO_UNIDAD: 'URBANO',
    CLAVE_TIPO_OBRA: 1,
    TIPO_OBRA: 'OBRA NUEVA',
    CLAVE_PROPIEDAD_DEL_INMUEBLE: 1,
    PROPIEDAD_DEL_INMUEBLE: 'PROPIO',
    LATITUD: 19.5784667,
    LONGITUD: -97.2421711,
    CLAVE_ULTIMO_MOVIMIENTO: 'A',
    ULTIMO_MOVIMIENTO: 'ALTA',
    FECHA_ULTIMO_MOVIMIENTO: '18/07/2024',
    COMENTARIOS_DE_LA_VALIDACION:
      'ESTABLECIMIENTO QUE PERTENECÍA A SECRETARIA DE SALUD DEL ESTADO, SE TRANSFIERE A SERVICIOS DE SALUD IMSS BIENESTAR.',
    CLAVE_MOTIVO_BAJA: '',
    MOTIVO_BAJA: '',
    FECHA_EFECTIVA_DE_BAJA: '',
  },
  {
    CLUES: 'VZIMB007493',
    CLAVE_DE_LA_INSTITUCION: 'IMB',
    NOMBRE_DE_LA_INSTITUCION: 'SERVICIOS DE SALUD IMSS BIENESTAR',
    CLAVE_DE_LA_ENTIDAD: 30,
    ENTIDAD: 'VERACRUZ DE IGNACIO DE LA LLAVE',
    CLAVE_DEL_MUNICIPIO: 182,
    MUNICIPIO: 'TLALNELHUAYOCAN',
    CLAVE_DE_LA_LOCALIDAD: 1,
    LOCALIDAD: 'TLALNELHUAYOCAN',
    CLAVE_DE_LA_JURISDICCION: 5,
    JURISDICCION: 'XALAPA',
    CLAVE_DEL_TIPO_ESTABLECIMIENTO: 1,
    NOMBRE_TIPO_ESTABLECIMIENTO: 'DE CONSULTA EXTERNA',
    CLAVE_DE_TIPOLOGIA: 'E',
    NOMBRE_DE_TIPOLOGIA: 'URBANO DE 02 NÚCLEOS BÁSICOS',
    CLAVE_DE_SUBTIPOLOGIA: 99,
    NOMBRE_DE_SUBTIPOLOGIA: 'NO ESPECIFICADO',
    NOMBRE_DE_LA_UNIDAD: 'SAN ANDRÉS TLALNELHUAYOCAN',
    NOMBRE_COMERCIAL: 'SAN ANDRÉS TLALNELHUAYOCAN',
    CLAVE_TIPO_DE_VIALIDAD: 5,
    TIPO_DE_VIALIDAD: 'CALLE',
    VIALIDAD: 'BENITO JUÁREZ',
    NUMERO_EXTERIOR: 'SIN NUMERO',
    NUMERO_INTERIOR: 'SIN NÚMERO',
    CLAVE_TIPO_DE_ASENTAMIENTO: 25,
    TIPO_DE_ASENTAMIENTO: 'PUEBLO',
    ASENTAMIENTO: 'TLALNELHUAYOCAN',
    CODIGO_POSTAL: '91230',
    OBSERVACIONES_DE_LA_DIRECCION:
      'ENTRE CALLES CARLOS A. CARRILLO Y RAFAEL RAMÍREZ',
    CLAVE_ESTATUS_DE_OPERACION: 1,
    ESTATUS_DE_OPERACION: 'EN OPERACION',
    FECHA_DE_CONSTRUCCION: '01/12/1999',
    FECHA_DE_INICIO_DE_OPERACION: '01/04/2009',
    CLAVE_UNIDAD_MOVIL_MARCA: '',
    UNIDAD_MOVIL_MARCA: '',
    UNIDAD_MOVIL_MARCA_ESPECIFICA: '',
    UNIDAD_MOVIL_MODELO: '',
    CLAVE_UNIDAD_MOVIL_PROGRAMA: '',
    UNIDAD_MOVIL_PROGRAMA: '',
    CLAVE_UNIDAD_MOVIL_TIPO: '',
    UNIDAD_MOVIL_TIPO: '',
    CLAVE_UNIDAD_MOVIL_TIPOLOGIA: '',
    UNIDAD_MOVIL_TIPOLOGIA: '',
    CLAVE_DE_LA_INS_ADM: 'IMB',
    NOMBRE_DE_LA_INS_ADM: 'SERVICIOS DE SALUD IMSS BIENESTAR',
    CLAVE_NIVEL_ATENCION: 1,
    NIVEL_ATENCION: 'PRIMER NIVEL',
    CLAVE_ESTRATO_UNIDAD: 2,
    ESTRATO_UNIDAD: 'URBANO',
    CLAVE_TIPO_OBRA: 5,
    TIPO_OBRA: 'OTRA',
    CLAVE_PROPIEDAD_DEL_INMUEBLE: 1,
    PROPIEDAD_DEL_INMUEBLE: 'PROPIO',
    LATITUD: 19.4250948,
    LONGITUD: -96.7966056,
    CLAVE_ULTIMO_MOVIMIENTO: 'A',
    ULTIMO_MOVIMIENTO: 'ALTA',
    FECHA_ULTIMO_MOVIMIENTO: '18/07/2024',
    COMENTARIOS_DE_LA_VALIDACION:
      'ESTABLECIMIENTO QUE PERTENECÍA A SECRETARIA DE SALUD DEL ESTADO, SE TRANSFIERE A SERVICIOS DE SALUD IMSS BIENESTAR.',
    CLAVE_MOTIVO_BAJA: '',
    MOTIVO_BAJA: '',
    FECHA_EFECTIVA_DE_BAJA: '',
  },
];
